# Generated by Django 2.1.7 on 2019-11-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(blank=True, null=True, verbose_name='チェックイン')),
                ('check_out', models.DateField(blank=True, null=True, verbose_name='チェックアウト')),
            ],
        ),
    ]
