# Generated by Django 2.1.7 on 2019-11-11 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Reservation',
        ),
    ]
