# Generated by Django 2.1.7 on 2019-11-29 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_auto_20191116_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='address3',
        ),
        migrations.AddField(
            model_name='reservation',
            name='number_choice',
            field=models.IntegerField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='0', null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='check_in',
            field=models.DateField(max_length=8, null=True, verbose_name='チェックイン'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='check_out',
            field=models.DateField(max_length=8, null=True, verbose_name='チェックアウト'),
        ),
    ]
