# Generated by Django 2.1.7 on 2019-11-29 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_auto_20191130_0827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='number_choice',
        ),
        migrations.AddField(
            model_name='reservation',
            name='number_adult',
            field=models.IntegerField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='0', null=True, verbose_name='人数(大人)'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='number_child',
            field=models.IntegerField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='0', null=True, verbose_name='人数(子供)'),
        ),
    ]
