# Generated by Django 2.1.7 on 2019-12-01 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_auto_20191130_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='check_in',
            field=models.DateField(null=True, verbose_name='チェックイン'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='check_out',
            field=models.DateField(null=True, verbose_name='チェックアウト'),
        ),
    ]
