# Generated by Django 2.1.7 on 2019-12-01 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0008_auto_20191201_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='number_adult',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='0', max_length=2, null=True, verbose_name='人数(大人)'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='number_child',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='0', max_length=2, null=True, verbose_name='人数(子供)'),
        ),
    ]
